# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vojtech Illner personal site
email: vojta.illner@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Vojtech Illner personal site with info, contacts and useful content.
logo: "/assets/images/mountain.png"
dateformat: "%B %-d, %Y"
twitter_username: username
github_username: username
minimal_mistakes_skin: dirt
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Vojtěch Illner"
  avatar : "/assets/images/sami_photo2.jpg"
  bio    : "Here you can find some relevant info together with useful links and manuals about things I worked on."
  location: Czech Republic
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/vojt%C4%9Bch-illner-5813471a3/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/vojtaiii"
    - label: "My band"
      icon: "fas fa-guitar"
      url: "https://www.facebook.com/roztrhlejdedac"
    - label: "Online punk radio app"
      icon: "fas fa-mobile"
      url: "https://radio.sumys.cz/"

footer:
  links:
    - label: "Contact"
      icon: "fa fa-at"
      url: "https://vojtaiii.github.io/personal_site/about/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_date: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
